travis:
  secure:
    BINSTAR_TOKEN: Y/hSRlfFmanTfSpozshWVspYPFHEsyOldPdaKC+PZXQl+ksGF0ZlOGGApXNIg42oKqEEF8RSDSXBaxN0mTZMaCD912lBG7jFWqMlwgDtTDlsujKAZYRKdyt21HsgtA+ArHJKjIAT6nzvv57K0jkaytK7E0GGH3O6qe5nHusFwJV4ajZv8lf/UXanW4NWafPQBrTXvFTXZQM598I8ZA/KvoE9crtRp4mbjcfSGRs9nHxANKJvqZiYeTIPifL9DRS0CZLDcC1Ipv1rL9HKvsCXZk1X0kmkCVo1G18cB17hX8KN/LJgMr2RYQ+QuDbEZssoSobLthY+vw5v5jfH8QTtV6dKDUpwXTfQLWWi6gNKCRHkZutzRajzP4zTc0PBU+4T76EKANR4ynLXs95vRLglpe8wL/9lXIVbon++Q6TUiN9A7fvSDE0utH7pe5ETSo33d/TDVyS6wReQvRWz/tUsWJdO5NK76RB1EUpC40doGMCx8o8wJDAp7O8xD69J4VeeeCm/HV54PnTZDPA12I8rMukxoh3B22ivO2cvykBa+9KrDsM6K0THjcnn31haTFdvOguHTY+SDlJHJYLPO8QZ7p8mOv2/659LgOeS1t7KkSoGVoTiZl9yLSuEnQ2I+sh5zpTTrsIQMV27lgasG7rQ/tVOIvMdgAZwj6qQgnwGzeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
